CC = gcc
CFLAGS = -Wall

run :
	$(CC) $(CFLAGS) job1.c -o job1
	$(CC) $(CFLAGS) job2.c -o job2
	$(CC) $(CFLAGS) job3.c -o job3
	$(CC) $(CFLAGS) job4.c -o job4

run_job1 :
	./job1

run_job2 :
	./job2

run_job3 :
	./job3

run_job4 :
	./job4

clean :
	rm job1 job2 job3 job4